---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:1.0
        ports:
        - containerPort: 80
        - containerPort: 9090
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 10
          periodSeconds: 10

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: application
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: application
spec:
  selector:
    app: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: healthz
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: application
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/health-check: "true"
    nginx.ingress.kubernetes.io/health-check-path: "/healthz"
    nginx.ingress.kubernetes.io/health-check-interval: "10"
    nginx.ingress.kubernetes.io/health-check-timeout: "5"
    nginx.ingress.kubernetes.io/health-check-unhealthy-threshold: "3"
    nginx.ingress.kubernetes.io/health-check-healthy-threshold: "2"
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
spec:
  ingressClassName: ingress-nginx
  rules:
  - host: frontend.example.com
    http:
      paths:
      - path: /healthz
        pathType: Exact
        backend:
          service:
            name: frontend-svc
            port:
              number: 9090
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-svc
            port:
              number: 80
  tls:
  - hosts:
    - frontend.example.com
    secretName: frontend-tls
        